package com.linksSaver.config;

import org.springframework.security.web.context.AbstractSecurityWebApplicationInitializer;

public class registerGlobalAuthenticationregisterGlobalAuthentication extends AbstractSecurityWebApplicationInitializer  {
}
